### ISSUE TITLE
slcontrol

### ISSUE THREAD

**Issue by prahjister** [jhdewitt/sltk#7]
I get these errors hovering over turn less turn more less scan and more scan

java.lang.NoSuchMethodError: processing.core.PVector.set(FFF)V
	at controlP5.Tooltip.activate(Unknown Source)
	at controlP5.Controller.setMouseOver(Unknown Source)
	at controlP5.Controller.updateEvents(Unknown Source)
	at controlP5.ControllerGroup.updateEvents(Unknown Source)
	at controlP5.ControlWindow.updateEvents(Unknown Source)
	at controlP5.ControlWindow.draw(Unknown Source)
	at controlP5.ControlWindow.draw(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1408)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1401)
	at processing.core.PApplet.handleMethods(PApplet.java:1600)
	at processing.core.PApplet.handleDraw(PApplet.java:2439)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by jhdewitt** [comment]
does this crash the program?
